
;Default Project
/DefaultProject=*%Applic_Root_Folder%UiExpert.edp

;Deployment Mode
/DeploymentMode = B

;/TempDatabase = SQLite Temp Database

/[MAGIC_LOGICAL_NAMES]Web_Application_Folder =*%Applic_Root_Folder%Angular\
/[MAGIC_DATABASES]UiExpert = DBMS, 10, , UiExpert.SQLite, , , , , NoMagicRecordLock, ChangeFileInToolkit, CheckDefinition, NoCheckKey, NoFileLocks, , , CheckExist, 0, , NoAS400SrvrSort,